# Generated by Django 5.2.4 on 2025-07-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="consume_slots",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="joker_slots",
            field=models.JSONField(default=list),
        ),
    ]
