# Generated by Django 5.2.4 on 2025-07-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_gamesession_consume_slots_gamesession_joker_slots"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="shop_data",
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name="Card",
        ),
    ]
