# Generated by Django 5.2.4 on 2025-07-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_gamesession_shop_data_delete_card"),
    ]

    operations = [
        migrations.CreateModel(
            name="RankRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=30)),
                ("score", models.PositiveIntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
